services:
  db:
    container_name: examly-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  node:
#    container_name: examly-node
#    image: node:alpine
#    entrypoint: /bin/sh
#    working_dir: /app
#    tty: true
#    volumes:
#      - ./resources:/app
#      - ./.env:/app/.env
#    ports:
#      - "5173:5173"