services:
  db:
    container_name: examly-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
