// Code generated by mockery v2.46.2. DO NOT EDIT.

package store

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUsersStore is an autogenerated mock type for the UsersStore type
type MockUsersStore struct {
	mock.Mock
}

type MockUsersStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersStore) EXPECT() *MockUsersStore_Expecter {
	return &MockUsersStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUsersStore) Create(ctx context.Context, user *User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsersStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUsersStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *User
func (_e *MockUsersStore_Expecter) Create(ctx interface{}, user interface{}) *MockUsersStore_Create_Call {
	return &MockUsersStore_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUsersStore_Create_Call) Run(run func(ctx context.Context, user *User)) *MockUsersStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*User))
	})
	return _c
}

func (_c *MockUsersStore_Create_Call) Return(_a0 error) *MockUsersStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsersStore_Create_Call) RunAndReturn(run func(context.Context, *User) error) *MockUsersStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockUsersStore) GetByEmail(ctx context.Context, email string) (User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStore_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUsersStore_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUsersStore_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUsersStore_GetByEmail_Call {
	return &MockUsersStore_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUsersStore_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUsersStore_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsersStore_GetByEmail_Call) Return(_a0 User, _a1 error) *MockUsersStore_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStore_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (User, error)) *MockUsersStore_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUsersStore) GetByID(ctx context.Context, id int) (User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUsersStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUsersStore_Expecter) GetByID(ctx interface{}, id interface{}) *MockUsersStore_GetByID_Call {
	return &MockUsersStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUsersStore_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockUsersStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUsersStore_GetByID_Call) Return(_a0 User, _a1 error) *MockUsersStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStore_GetByID_Call) RunAndReturn(run func(context.Context, int) (User, error)) *MockUsersStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUsersStore) Update(ctx context.Context, user *User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsersStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUsersStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *User
func (_e *MockUsersStore_Expecter) Update(ctx interface{}, user interface{}) *MockUsersStore_Update_Call {
	return &MockUsersStore_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUsersStore_Update_Call) Run(run func(ctx context.Context, user *User)) *MockUsersStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*User))
	})
	return _c
}

func (_c *MockUsersStore_Update_Call) Return(_a0 error) *MockUsersStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsersStore_Update_Call) RunAndReturn(run func(context.Context, *User) error) *MockUsersStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersStore creates a new instance of MockUsersStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersStore {
	mock := &MockUsersStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
