// Code generated by mockery v2.46.2. DO NOT EDIT.

package store

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockModulesStore is an autogenerated mock type for the ModulesStore type
type MockModulesStore struct {
	mock.Mock
}

type MockModulesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModulesStore) EXPECT() *MockModulesStore_Expecter {
	return &MockModulesStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, course
func (_m *MockModulesStore) Create(ctx context.Context, course *Module) error {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Module) error); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModulesStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockModulesStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - course *Module
func (_e *MockModulesStore_Expecter) Create(ctx interface{}, course interface{}) *MockModulesStore_Create_Call {
	return &MockModulesStore_Create_Call{Call: _e.mock.On("Create", ctx, course)}
}

func (_c *MockModulesStore_Create_Call) Run(run func(ctx context.Context, course *Module)) *MockModulesStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Module))
	})
	return _c
}

func (_c *MockModulesStore_Create_Call) Return(_a0 error) *MockModulesStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModulesStore_Create_Call) RunAndReturn(run func(context.Context, *Module) error) *MockModulesStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx
func (_m *MockModulesStore) Get(ctx context.Context) ([]Module, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []Module
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Module, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Module); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Module)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModulesStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockModulesStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockModulesStore_Expecter) Get(ctx interface{}) *MockModulesStore_Get_Call {
	return &MockModulesStore_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockModulesStore_Get_Call) Run(run func(ctx context.Context)) *MockModulesStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockModulesStore_Get_Call) Return(_a0 []Module, _a1 error) *MockModulesStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModulesStore_Get_Call) RunAndReturn(run func(context.Context) ([]Module, error)) *MockModulesStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModulesStore creates a new instance of MockModulesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModulesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModulesStore {
	mock := &MockModulesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
