// Code generated by mockery v2.46.2. DO NOT EDIT.

package store

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserAnswersStore is an autogenerated mock type for the UserAnswersStore type
type MockUserAnswersStore struct {
	mock.Mock
}

type MockUserAnswersStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAnswersStore) EXPECT() *MockUserAnswersStore_Expecter {
	return &MockUserAnswersStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, answer
func (_m *MockUserAnswersStore) Create(ctx context.Context, answer *UserAnswer) error {
	ret := _m.Called(ctx, answer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UserAnswer) error); ok {
		r0 = rf(ctx, answer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserAnswersStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserAnswersStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - answer *UserAnswer
func (_e *MockUserAnswersStore_Expecter) Create(ctx interface{}, answer interface{}) *MockUserAnswersStore_Create_Call {
	return &MockUserAnswersStore_Create_Call{Call: _e.mock.On("Create", ctx, answer)}
}

func (_c *MockUserAnswersStore_Create_Call) Run(run func(ctx context.Context, answer *UserAnswer)) *MockUserAnswersStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*UserAnswer))
	})
	return _c
}

func (_c *MockUserAnswersStore_Create_Call) Return(_a0 error) *MockUserAnswersStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserAnswersStore_Create_Call) RunAndReturn(run func(context.Context, *UserAnswer) error) *MockUserAnswersStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAnswersStore creates a new instance of MockUserAnswersStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAnswersStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAnswersStore {
	mock := &MockUserAnswersStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
